<?php
/**
 * Authenticated download endpoint for a bulk-export zip generated by bulk_action.php.
 * The zip's contents were already permission-filtered when it was built, so this only
 * requires a valid session plus proof that this specific file was generated for it.
 */
require_once 'includes/bootstrap.php';
require_once BASE_PATH . '/includes/auth_validate.php';

$file = basename($_GET['file'] ?? '');

if (!preg_match('/^qrcodes_[0-9a-f]+\.zip$/', $file)) {
    http_response_code(404);
    exit('Not found');
}

if (empty($_SESSION['generated_zips']) || !in_array($file, $_SESSION['generated_zips'], true)) {
    http_response_code(403);
    exit('Forbidden');
}

$path = SAVED_QRCODE_DIRECTORY . 'zip/' . $file;

if (!is_file($path)) {
    http_response_code(404);
    exit('Not found');
}

header('Content-Type: application/zip');
header('Content-Length: ' . filesize($path));
header('Content-Disposition: attachment; filename="' . $file . '"');

readfile($path);
exit;
